In [8]:
import numpy as np
import pandas as pd
from sklearn import svm

In [9]:
data = np.genfromtxt('data/svm-data.csv', delimiter=",")
X = data[:,1:]
y = data[:,0]


In [10]:
clf = svm.SVC(C=100000, kernel='linear', random_state=241)
clf.fit(X, y)

SVC(C=100000, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=241, shrinking=True,
  tol=0.001, verbose=False)

In [11]:
clf.support_

array([3, 4, 9], dtype=int32)

In [12]:
clf.support_vectors_

array([[ 0.98,  0.68],
       [ 0.48,  0.39],
       [ 0.53,  0.53]])

# Answer

In [16]:
clf.support_ + 1

array([ 4,  5, 10], dtype=int32)